# Generated by Django 3.1.5 on 2021-01-20 07:57

import covidapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=covidapi.models.nameFile)),
                ('result', models.CharField(choices=[('NA', 'None'), ('P', 'Positive'), ('N', 'Negative')], default='NA', max_length=10)),
            ],
        ),
    ]
